//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAO_REUNIAO
    {
        public int ID_ACAO_REUNIAO { get; set; }
        public int ID_ACAO { get; set; }
        public int ID_REUNIAO { get; set; }
    
        public virtual ACAO ACAO { get; set; }
        public virtual REUNIAO REUNIAO { get; set; }
    }
}
