//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO_AMC
    {
        public ALUNO_AMC()
        {
            this.ALUNO_AMC1 = new HashSet<ALUNO_AMC>();
            this.ALUNO_AMC11 = new HashSet<ALUNO_AMC>();
        }
    
        public Nullable<int> ID_AMC { get; set; }
        public Nullable<int> ID_ALUNO_MATRICULA { get; set; }
        public int ID_ALUNO_AMC { get; set; }
        public string NOTA { get; set; }
        public Nullable<int> CLASSIFICACAO { get; set; }
    
        public virtual ICollection<ALUNO_AMC> ALUNO_AMC1 { get; set; }
        public virtual ALUNO_AMC ALUNO_AMC2 { get; set; }
        public virtual ICollection<ALUNO_AMC> ALUNO_AMC11 { get; set; }
        public virtual ALUNO_AMC ALUNO_AMC3 { get; set; }
    }
}
