//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO
    {
        public ALUNO()
        {
            this.ALUNO_MATRICULA = new HashSet<ALUNO_MATRICULA>();
        }
    
        public int ID_ALUNO { get; set; }
        public Nullable<int> RA { get; set; }
        public Nullable<int> ID_PESSOA { get; set; }
        public Nullable<bool> ATIVO { get; set; }
    
        public virtual ICollection<ALUNO_MATRICULA> ALUNO_MATRICULA { get; set; }
        public virtual PESSOA PESSOA { get; set; }
    }
}
