//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public CURSO()
        {
            this.CURSO_COORDENADOR = new HashSet<CURSO_COORDENADOR>();
            this.DISCIPLINA = new HashSet<DISCIPLINA>();
        }
    
        public int ID_CURSO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<CURSO_COORDENADOR> CURSO_COORDENADOR { get; set; }
        public virtual ICollection<DISCIPLINA> DISCIPLINA { get; set; }
    }
}
