//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LANCAMENTO
    {
        public LANCAMENTO()
        {
            this.LANCAMENTO1 = new HashSet<LANCAMENTO>();
        }
    
        public int ID_LANCAMENTO { get; set; }
        public Nullable<int> ID_TURMA { get; set; }
        public Nullable<int> ID_TIPOLANCAMENTO { get; set; }
        public Nullable<System.DateTime> DATA_LANCAMENTO { get; set; }
        public Nullable<int> ID_SEMESTRE { get; set; }
        public string JUSTIFICATIVA { get; set; }
        public string PROVIDENCIA { get; set; }
        public Nullable<int> ID_DISCIPLINA { get; set; }
        public Nullable<int> ID_FUNCIONARIO { get; set; }
    
        public virtual DISCIPLINA DISCIPLINA { get; set; }
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual ICollection<LANCAMENTO> LANCAMENTO1 { get; set; }
        public virtual LANCAMENTO LANCAMENTO2 { get; set; }
        public virtual TIPO_LANCAMENTO TIPO_LANCAMENTO { get; set; }
        public virtual TURMA TURMA { get; set; }
    }
}
