//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECEntities : DbContext
    {
        public ECEntities()
            : base("name=ECEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACAO> ACAO { get; set; }
        public DbSet<ACAO_AMC> ACAO_AMC { get; set; }
        public DbSet<ACAO_EVENTO> ACAO_EVENTO { get; set; }
        public DbSet<ACAO_REUNIAO> ACAO_REUNIAO { get; set; }
        public DbSet<ALUNO> ALUNO { get; set; }
        public DbSet<ALUNO_AMC> ALUNO_AMC { get; set; }
        public DbSet<ALUNO_MATRICULA> ALUNO_MATRICULA { get; set; }
        public DbSet<AMC> AMC { get; set; }
        public DbSet<CARGO> CARGO { get; set; }
        public DbSet<CURSO> CURSO { get; set; }
        public DbSet<CURSO_COORDENADOR> CURSO_COORDENADOR { get; set; }
        public DbSet<DISCIPLINA> DISCIPLINA { get; set; }
        public DbSet<DISCIPLINA_PROFESSOR> DISCIPLINA_PROFESSOR { get; set; }
        public DbSet<EVENTO> EVENTO { get; set; }
        public DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public DbSet<LANCAMENTO> LANCAMENTO { get; set; }
        public DbSet<PESSOA> PESSOA { get; set; }
        public DbSet<PRIORIDADE_ACAO> PRIORIDADE_ACAO { get; set; }
        public DbSet<PROVA> PROVA { get; set; }
        public DbSet<QUESTAO> QUESTAO { get; set; }
        public DbSet<REPRESENTANTE_TURMA> REPRESENTANTE_TURMA { get; set; }
        public DbSet<RESPOSTA> RESPOSTA { get; set; }
        public DbSet<REUNIAO> REUNIAO { get; set; }
        public DbSet<REUNIAO_ASSUNTO_TRATADO> REUNIAO_ASSUNTO_TRATADO { get; set; }
        public DbSet<REUNIAO_ATA> REUNIAO_ATA { get; set; }
        public DbSet<REUNIAO_COMPROMISSO> REUNIAO_COMPROMISSO { get; set; }
        public DbSet<REUNIAO_PARTICIPANTE> REUNIAO_PARTICIPANTE { get; set; }
        public DbSet<REUNIAO_PAUTA> REUNIAO_PAUTA { get; set; }
        public DbSet<SEMESTRE> SEMESTRE { get; set; }
        public DbSet<STATUS_ACAO> STATUS_ACAO { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TIPO_ASSUNTO_TRATADO> TIPO_ASSUNTO_TRATADO { get; set; }
        public DbSet<TIPO_EVENTO> TIPO_EVENTO { get; set; }
        public DbSet<TIPO_LANCAMENTO> TIPO_LANCAMENTO { get; set; }
        public DbSet<TIPO_REPRESENTANTE> TIPO_REPRESENTANTE { get; set; }
        public DbSet<TIPO_REUNIAO> TIPO_REUNIAO { get; set; }
        public DbSet<TIPO_TURMA> TIPO_TURMA { get; set; }
        public DbSet<TURMA> TURMA { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
