//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPRESENTANTE_TURMA
    {
        public int ID_REPRESENTANTE { get; set; }
        public Nullable<int> ID_TIPOREPRESENTANTE { get; set; }
        public Nullable<int> ID_ALUNO_MATRICULA { get; set; }
        public Nullable<int> ID_TURMA { get; set; }
    
        public virtual ALUNO_MATRICULA ALUNO_MATRICULA { get; set; }
        public virtual TURMA TURMA { get; set; }
        public virtual TIPO_REPRESENTANTE TIPO_REPRESENTANTE { get; set; }
    }
}
