//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPOSTA
    {
        public int ID_RESPOSTA { get; set; }
        public Nullable<int> ID_QUESTAO { get; set; }
        public string TEXTO { get; set; }
        public Nullable<bool> RESPOSTA_CORRETA { get; set; }
    
        public virtual QUESTAO QUESTAO { get; set; }
    }
}
