//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class REUNIAO_ATA
    {
        public int ID_ATA { get; set; }
        public int ID_REUNIAO { get; set; }
        public int ID_FUNCIONARIO_RESPOSAVEL { get; set; }
        public Nullable<System.DateTime> DATA_FECHAMENTO { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual REUNIAO REUNIAO { get; set; }
    }
}
