//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class REUNIAO_PARTICIPANTE
    {
        public int ID_PARTICIPANTE { get; set; }
        public int ID_REUNIAO { get; set; }
        public Nullable<bool> PRESENCA { get; set; }
        public int ID_PESSOA { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
        public virtual REUNIAO REUNIAO { get; set; }
    }
}
