//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class REUNIAO_ATA
    {
        public int ID_ATA { get; set; }
        public int ID_REUNIAO { get; set; }
        public int ID_FUNCIONARIO_RESPOSAVEL { get; set; }
        public Nullable<System.DateTime> DATA_FECHAMENTO { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual REUNIAO REUNIAO { get; set; }
    }
}
