//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_REPRESENTANTE
    {
        public TIPO_REPRESENTANTE()
        {
            this.REPRESENTANTE_TURMA = new HashSet<REPRESENTANTE_TURMA>();
        }
    
        public int ID_TIPOREPRESENTANTE { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<REPRESENTANTE_TURMA> REPRESENTANTE_TURMA { get; set; }
    }
}
