//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_TURMA
    {
        public TIPO_TURMA()
        {
            this.TURMA = new HashSet<TURMA>();
        }
    
        public int ID_TIPOTURMA { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<TURMA> TURMA { get; set; }
    }
}
