//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_EVENTO
    {
        public TIPO_EVENTO()
        {
            this.EVENTO = new HashSet<EVENTO>();
        }
    
        public int ID_TIPOEVENTO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<EVENTO> EVENTO { get; set; }
    }
}
