//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_LANCAMENTO
    {
        public TIPO_LANCAMENTO()
        {
            this.LANCAMENTO = new HashSet<LANCAMENTO>();
        }
    
        public int ID_TIPOLANCAMENTO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<LANCAMENTO> LANCAMENTO { get; set; }
    }
}
