//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_EVENTO
    {
        public TIPO_EVENTO()
        {
            this.EVENTO = new HashSet<EVENTO>();
        }
    
        public int ID_TIPOEVENTO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<EVENTO> EVENTO { get; set; }
    }
}
