//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURMA
    {
        public TURMA()
        {
            this.ALUNO_MATRICULA = new HashSet<ALUNO_MATRICULA>();
            this.LANCAMENTO = new HashSet<LANCAMENTO>();
            this.REPRESENTANTE_TURMA = new HashSet<REPRESENTANTE_TURMA>();
        }
    
        public int ID_TURMA { get; set; }
        public Nullable<int> ID_TIPOTURMA { get; set; }
        public Nullable<int> ID_SEMESTRE { get; set; }
        public Nullable<int> PERIODO_CURSO { get; set; }
        public Nullable<System.DateTime> DATA_INICIOAULA { get; set; }
        public Nullable<int> NUMERO_VAGAS { get; set; }
    
        public virtual ICollection<ALUNO_MATRICULA> ALUNO_MATRICULA { get; set; }
        public virtual ICollection<LANCAMENTO> LANCAMENTO { get; set; }
        public virtual ICollection<REPRESENTANTE_TURMA> REPRESENTANTE_TURMA { get; set; }
        public virtual SEMESTRE SEMESTRE { get; set; }
        public virtual TIPO_TURMA TIPO_TURMA { get; set; }
    }
}
