//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAO_REUNIAO
    {
        public int ID_ACAO_REUNIAO { get; set; }
        public int ID_ACAO { get; set; }
        public int ID_REUNIAO { get; set; }
    
        public virtual ACAO ACAO { get; set; }
        public virtual REUNIAO REUNIAO { get; set; }
    }
}
