//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO_AMC
    {
        public ALUNO_AMC()
        {
            this.ALUNO_AMC_QUESTAO = new HashSet<ALUNO_AMC_QUESTAO>();
        }
    
        public int ID_ALUNO_AMC { get; set; }
        public int ID_AMC { get; set; }
        public int ID_ALUNO_MATRICULA { get; set; }
        public string NOTA { get; set; }
        public Nullable<int> CLASSIFICACAO { get; set; }
        public Nullable<int> NUMERO_ACERTOS { get; set; }
    
        public virtual ALUNO_MATRICULA ALUNO_MATRICULA { get; set; }
        public virtual AMC AMC { get; set; }
        public virtual ICollection<ALUNO_AMC_QUESTAO> ALUNO_AMC_QUESTAO { get; set; }
    }
}
