//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO_AMC_QUESTAO
    {
        public int ID_ALUNO_AMC_QUESTAO { get; set; }
        public int ID_QUESTAO { get; set; }
        public int ID_ALUNO_AMC { get; set; }
        public Nullable<decimal> NOTA { get; set; }
    
        public virtual ALUNO_AMC ALUNO_AMC { get; set; }
        public virtual QUESTAO QUESTAO { get; set; }
    }
}
