//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMC
    {
        public AMC()
        {
            this.ACAO_AMC = new HashSet<ACAO_AMC>();
            this.QUESTAO = new HashSet<QUESTAO>();
        }
    
        public int ID_AMC { get; set; }
        public Nullable<System.DateTime> DATA_APLICACAO { get; set; }
        public Nullable<int> ID_SEMESTRE { get; set; }
    
        public virtual ICollection<ACAO_AMC> ACAO_AMC { get; set; }
        public virtual SEMESTRE SEMESTRE { get; set; }
        public virtual ICollection<QUESTAO> QUESTAO { get; set; }
    }
}
