//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCIPLINA_PROFESSOR
    {
        public int ID_DISCIPLINA_PROFESSOR { get; set; }
        public int ID_DISCIPLINA { get; set; }
        public int ID_FUNCIONARIO { get; set; }
    
        public virtual DISCIPLINA DISCIPLINA { get; set; }
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
    }
}
