//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public EVENTO()
        {
            this.ACAO_EVENTO = new HashSet<ACAO_EVENTO>();
            this.EVENTO1 = new HashSet<EVENTO>();
        }
    
        public int ID_EVENTO { get; set; }
        public Nullable<int> ID_TIPOEVENTO { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public string LOCAL { get; set; }
        public Nullable<System.DateTime> INICIO { get; set; }
        public Nullable<System.DateTime> CONCLUSAO { get; set; }
        public Nullable<int> ID_PESSOA { get; set; }
        public Nullable<int> ID_SEMESTRE { get; set; }
    
        public virtual ICollection<ACAO_EVENTO> ACAO_EVENTO { get; set; }
        public virtual PESSOA PESSOA { get; set; }
        public virtual ICollection<EVENTO> EVENTO1 { get; set; }
        public virtual EVENTO EVENTO2 { get; set; }
        public virtual TIPO_EVENTO TIPO_EVENTO { get; set; }
    }
}
