//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESSOA
    {
        public PESSOA()
        {
            this.ACAO = new HashSet<ACAO>();
            this.ALUNO = new HashSet<ALUNO>();
            this.EVENTO = new HashSet<EVENTO>();
            this.FUNCIONARIO = new HashSet<FUNCIONARIO>();
            this.REUNIAO_COMPROMISSO = new HashSet<REUNIAO_COMPROMISSO>();
            this.REUNIAO_PARTICIPANTE = new HashSet<REUNIAO_PARTICIPANTE>();
        }
    
        public int ID_PESSOA { get; set; }
        public string NOME { get; set; }
        public string TELEFONE { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<ACAO> ACAO { get; set; }
        public virtual ICollection<ALUNO> ALUNO { get; set; }
        public virtual ICollection<EVENTO> EVENTO { get; set; }
        public virtual ICollection<FUNCIONARIO> FUNCIONARIO { get; set; }
        public virtual ICollection<REUNIAO_COMPROMISSO> REUNIAO_COMPROMISSO { get; set; }
        public virtual ICollection<REUNIAO_PARTICIPANTE> REUNIAO_PARTICIPANTE { get; set; }
    }
}
