//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIORIDADE_ACAO
    {
        public PRIORIDADE_ACAO()
        {
            this.ACAO = new HashSet<ACAO>();
        }
    
        public int ID_PRIORIDADE { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<ACAO> ACAO { get; set; }
    }
}
