//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class REUNIAO_PAUTA
    {
        public int ID_PAUTA { get; set; }
        public Nullable<int> ID_REUNIAO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> ITEM { get; set; }
    
        public virtual REUNIAO REUNIAO { get; set; }
    }
}
