//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEMESTRE
    {
        public SEMESTRE()
        {
            this.AMC = new HashSet<AMC>();
            this.REUNIAO = new HashSet<REUNIAO>();
            this.TURMA = new HashSet<TURMA>();
        }
    
        public int ID_SEMESTRE { get; set; }
        public int ANO { get; set; }
        public int SEMESTRE1 { get; set; }
        public bool ATIVO { get; set; }
    
        public virtual ICollection<AMC> AMC { get; set; }
        public virtual ICollection<REUNIAO> REUNIAO { get; set; }
        public virtual ICollection<TURMA> TURMA { get; set; }
    }
}
