//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ASSUNTO_TRATADO
    {
        public TIPO_ASSUNTO_TRATADO()
        {
            this.REUNIAO_ASSUNTO_TRATADO = new HashSet<REUNIAO_ASSUNTO_TRATADO>();
        }
    
        public int ID_TIPOASSTRATADO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<REUNIAO_ASSUNTO_TRATADO> REUNIAO_ASSUNTO_TRATADO { get; set; }
    }
}
