//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_REUNIAO
    {
        public TIPO_REUNIAO()
        {
            this.REUNIAO = new HashSet<REUNIAO>();
        }
    
        public int ID_TIPOREUNIAO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<REUNIAO> REUNIAO { get; set; }
    }
}
