//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public bool ATIVO { get; set; }
        public string SENHA { get; set; }
        public byte[] FOTO { get; set; }
        public int ID_FUNCIONARIO { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
    }
}
