//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAO
    {
        public ACAO()
        {
            this.ACAO_REUNIAO = new HashSet<ACAO_REUNIAO>();
            this.ACAO_AMC = new HashSet<ACAO_AMC>();
            this.ACAO_EVENTO = new HashSet<ACAO_EVENTO>();
        }
    
        public int ID_ACAO { get; set; }
        public string TITULO { get; set; }
        public Nullable<System.DateTime> INICIO { get; set; }
        public Nullable<System.DateTime> CONCLUSAO { get; set; }
        public Nullable<int> ID_STATUS { get; set; }
        public Nullable<int> ID_PRIORIDADE { get; set; }
        public Nullable<int> ID_PESSOA { get; set; }
    
        public virtual ICollection<ACAO_REUNIAO> ACAO_REUNIAO { get; set; }
        public virtual ICollection<ACAO_AMC> ACAO_AMC { get; set; }
        public virtual ICollection<ACAO_EVENTO> ACAO_EVENTO { get; set; }
        public virtual STATUS_ACAO STATUS_ACAO { get; set; }
        public virtual PRIORIDADE_ACAO PRIORIDADE_ACAO { get; set; }
        public virtual PESSOA PESSOA { get; set; }
    }
}
