//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESSOA
    {
        public PESSOA()
        {
            this.ALUNO = new HashSet<ALUNO>();
            this.COMPROMISSO = new HashSet<COMPROMISSO>();
            this.FUNCIONARIO = new HashSet<FUNCIONARIO>();
            this.ACAO = new HashSet<ACAO>();
            this.EVENTO = new HashSet<EVENTO>();
        }
    
        public int ID_PESSOA { get; set; }
        public string NOME { get; set; }
        public string TELEFONE { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<ALUNO> ALUNO { get; set; }
        public virtual ICollection<COMPROMISSO> COMPROMISSO { get; set; }
        public virtual ICollection<FUNCIONARIO> FUNCIONARIO { get; set; }
        public virtual ICollection<ACAO> ACAO { get; set; }
        public virtual ICollection<EVENTO> EVENTO { get; set; }
    }
}
