//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ASSUNTO_TRATADO
    {
        public TIPO_ASSUNTO_TRATADO()
        {
            this.ASSUNTO_TRATADO = new HashSet<ASSUNTO_TRATADO>();
        }
    
        public int ID_TIPOASSTRATADO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<ASSUNTO_TRATADO> ASSUNTO_TRATADO { get; set; }
    }
}
