//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO_AMC
    {
        public int ID_ALUNOAMC { get; set; }
        public int ID_AMC { get; set; }
        public int ID_ALUNOCURSO { get; set; }
        public string NOTA { get; set; }
        public Nullable<int> CLASIFICACAO { get; set; }
    
        public virtual AMC AMC { get; set; }
        public virtual ALUNO_CURSO ALUNO_CURSO { get; set; }
    }
}
