//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO
    {
        public ALUNO()
        {
            this.ALUNO_CURSO = new HashSet<ALUNO_CURSO>();
            this.PARTICIPANTE = new HashSet<PARTICIPANTE>();
        }
    
        public int ID_ALUNO { get; set; }
        public Nullable<int> RA { get; set; }
        public Nullable<int> ID_PESSOA { get; set; }
    
        public virtual ICollection<ALUNO_CURSO> ALUNO_CURSO { get; set; }
        public virtual ICollection<PARTICIPANTE> PARTICIPANTE { get; set; }
        public virtual PESSOA PESSOA { get; set; }
    }
}
