//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCIPLINA
    {
        public DISCIPLINA()
        {
            this.QUESTAO = new HashSet<QUESTAO>();
        }
    
        public int ID_DISCIPLINA { get; set; }
        public Nullable<int> ID_CURSO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<QUESTAO> QUESTAO { get; set; }
        public virtual CURSO CURSO { get; set; }
    }
}
