//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public EVENTO()
        {
            this.ACAO_EVENTO = new HashSet<ACAO_EVENTO>();
        }
    
        public int ID_EVENTO { get; set; }
        public Nullable<int> ID_TIPOEVENTO { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public string LOCAL { get; set; }
        public Nullable<System.DateTime> INICIO { get; set; }
        public Nullable<System.DateTime> CONCLUSAO { get; set; }
        public Nullable<int> ID_PESSOA { get; set; }
    
        public virtual ICollection<ACAO_EVENTO> ACAO_EVENTO { get; set; }
        public virtual PESSOA PESSOA { get; set; }
        public virtual TIPO_EVENTO TIPO_EVENTO { get; set; }
    }
}
