//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public FUNCIONARIO()
        {
            this.QUESTAO = new HashSet<QUESTAO>();
            this.PARTICIPANTE = new HashSet<PARTICIPANTE>();
            this.TURMA = new HashSet<TURMA>();
        }
    
        public int ID_FUNCIONARIO { get; set; }
        public Nullable<int> MATRICULA { get; set; }
        public Nullable<int> ID_CARGO { get; set; }
        public Nullable<int> ID_PESSOA { get; set; }
    
        public virtual ICollection<QUESTAO> QUESTAO { get; set; }
        public virtual CARGO CARGO { get; set; }
        public virtual PESSOA PESSOA { get; set; }
        public virtual ICollection<PARTICIPANTE> PARTICIPANTE { get; set; }
        public virtual ICollection<TURMA> TURMA { get; set; }
    }
}
