//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ALICE2Entities : DbContext
    {
        public ALICE2Entities()
            : base("name=ALICE2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<REUNIAO> REUNIAO { get; set; }
        public DbSet<ACAO_REUNIAO> ACAO_REUNIAO { get; set; }
        public DbSet<ASSUNTO_TRATADO> ASSUNTO_TRATADO { get; set; }
        public DbSet<COMPROMISSO> COMPROMISSO { get; set; }
        public DbSet<PAUTA_REUNIAO> PAUTA_REUNIAO { get; set; }
        public DbSet<EVENTO> EVENTO { get; set; }
        public DbSet<DISCIPLINA> DISCIPLINA { get; set; }
        public DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public DbSet<ACAO> ACAO { get; set; }
        public DbSet<ACAO_AMC> ACAO_AMC { get; set; }
        public DbSet<ACAO_EVENTO> ACAO_EVENTO { get; set; }
        public DbSet<AMC> AMC { get; set; }
        public DbSet<QUESTAO> QUESTAO { get; set; }
        public DbSet<ALUNO> ALUNO { get; set; }
        public DbSet<ALUNO_AMC> ALUNO_AMC { get; set; }
        public DbSet<ALUNO_CURSO> ALUNO_CURSO { get; set; }
        public DbSet<CARGO> CARGO { get; set; }
        public DbSet<LANCAMENTO> LANCAMENTO { get; set; }
        public DbSet<PARTICIPANTE> PARTICIPANTE { get; set; }
        public DbSet<PESSOA> PESSOA { get; set; }
        public DbSet<PRIORIDADE_ACAO> PRIORIDADE_ACAO { get; set; }
        public DbSet<REPRESENTANTE_TURMA> REPRESENTANTE_TURMA { get; set; }
        public DbSet<STATUS_ACAO> STATUS_ACAO { get; set; }
        public DbSet<TIPO_ASSUNTO_TRATADO> TIPO_ASSUNTO_TRATADO { get; set; }
        public DbSet<TIPO_LANCAMENTO> TIPO_LANCAMENTO { get; set; }
        public DbSet<TIPO_REPRESENTANTE> TIPO_REPRESENTANTE { get; set; }
        public DbSet<TURMA> TURMA { get; set; }
        public DbSet<CURSO> CURSO { get; set; }
        public DbSet<RESPOSTA> RESPOSTA { get; set; }
        public DbSet<TIPO_REUNIAO> TIPO_REUNIAO { get; set; }
        public DbSet<TIPO_EVENTO> TIPO_EVENTO { get; set; }
        public DbSet<TIPO_TURMA> TIPO_TURMA { get; set; }
    }
}
