//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTE
    {
        public int ID_PARTICIPANTE { get; set; }
        public Nullable<int> ID_FUNCIONARIO { get; set; }
        public Nullable<int> ID_ALUNO { get; set; }
        public Nullable<int> ID_REUNIAO { get; set; }
        public Nullable<bool> PRESENCA { get; set; }
    
        public virtual ALUNO ALUNO { get; set; }
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual REUNIAO REUNIAO { get; set; }
    }
}
