//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPRESENTANTE_TURMA
    {
        public int ID_REPRESENTANTE { get; set; }
        public Nullable<int> ID_TIPOREPRESENTANTE { get; set; }
        public Nullable<int> ID_ALUNOCURSO { get; set; }
        public Nullable<int> ID_TURMA { get; set; }
    
        public virtual ALUNO_CURSO ALUNO_CURSO { get; set; }
        public virtual TIPO_REPRESENTANTE TIPO_REPRESENTANTE { get; set; }
        public virtual TURMA TURMA { get; set; }
    }
}
