//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURMA
    {
        public TURMA()
        {
            this.LANCAMENTO = new HashSet<LANCAMENTO>();
            this.REPRESENTANTE_TURMA = new HashSet<REPRESENTANTE_TURMA>();
            this.ALUNO_CURSO1 = new HashSet<ALUNO_CURSO>();
        }
    
        public int ID_TURMA { get; set; }
        public Nullable<int> ID_DISCIPLINA { get; set; }
        public Nullable<int> ID_FUNCIONARIO { get; set; }
        public Nullable<int> ID_TIPOTURMA { get; set; }
        public Nullable<int> SEMESTRE { get; set; }
        public Nullable<int> ANO { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual ICollection<LANCAMENTO> LANCAMENTO { get; set; }
        public virtual ICollection<REPRESENTANTE_TURMA> REPRESENTANTE_TURMA { get; set; }
        public virtual TIPO_TURMA TIPO_TURMA { get; set; }
        public virtual ICollection<ALUNO_CURSO> ALUNO_CURSO1 { get; set; }
    }
}
