//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.UI.WebControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EC.UI.WebControls.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;230&quot; border=&quot;0&quot; bgcolor=&quot;#FF0000&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td width=&quot;10&quot;&gt;
        ///                            &lt;img height=&quot;10&quot; src=&quot;#PATHIMAGES#borda_esq_top.png&quot; width=&quot;10&quot;&gt;&lt;/td&gt;
        ///                        &lt;td background=&quot;#PATHIMAGES#borda_top_back.png&quot;&gt;
        ///                            &lt;img height=&quot;10&quot; src=&quot;#PATHIMAGES#vazio.gif&quot; width=&quot;10&quot;&gt;&lt;/td&gt;
        ///                        &lt;td width=&quot;10&quot;&gt;
        ///                            &lt;img height=&quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlAlertPortal {
            get {
                return ResourceManager.GetString("HtmlAlertPortal", resourceCulture);
            }
        }
    }
}
